### ISSUE TITLE
pip-faster may install un-available package versions due to wheel cache

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/venv-update#103]
Demo:
- a project with a custom PyPI server which has only flake8 version 2.3.0
- a project with a `requirements.txt` of unpinned `flake8`
- a flake8 2.5.1 wheel already in my wheelhouse (from another project which uses public PyPI) `/nail/home/ckuehl/.cache/pip-faster/wheelhouse/flake8-2.5.1-py2.py3-none-any.whl`

`pip-faster install -i https://my.pypi.server/simple flake8` will mistakenly install version 2.5.1 instead of 2.3.0 which means I'll be using a different version than the rest of my team. And if I freeze requirements and ship them, it will pin a version that nobody else can install.

**Comment by bukzor** [comment]
That is a conundrum. It certainly doesn't satisfy the contract of "your virtualenv is the same as if you re-installed it from scratch".

Do you have any proposed solution?

**Comment by bukzor** [comment]
Perhaps we shouldn't put the pip-faster wheelhouse into --find-links.

**Comment by ENuge** [comment]
This happened with a few packages I had installed locally. Only noticed after shipping when the CI builds failed because the private PyPi didn't have the pinned versions.

**Comment by bukzor** [comment]
@chriskuehl @asottile Any ideas on how we should solve this? I'm stumped. 

Maybe the best I can do is make it a "known issue".

**Comment by asottile** [comment]
@bukzor we talked about this already irl -- encode the index url in the path that the packages are stored in the same way pip does

**Comment by bukzor** [comment]
That won't help in the case that we take a package off of our server. Is
that good enough?

**Comment by asottile** [comment]
I think that's fine

**Comment by bukzor** [comment]
That said, the only way to implement this without adding hundreds of lines of code is to upgrade to pip>1.

Blocked by: #27
