### ISSUE TITLE
OSX support

### ISSUE THREAD

**Issue by kentwills** [Yelp/venv-update#108]
I currently don't have access to python 3.4 on my OSX box, but here is the repro with python 3.5:

http://paste.pound-python.org/show/ypTUsScHfGagXeZ2NM9f/

**Comment by bukzor** [comment]
This is on the back burner since we're not using osx.

**Comment by asottile** [comment]
Should try this again, there's been at least one patch about this that might have fixed it.  @kentwills  can you give this another shot against 2.0.0?

**Comment by kentwills** [comment]
Tested locally, works since #170.
