### ISSUE TITLE
"extras" are always pruned on subsequent runs

### ISSUE THREAD

**Issue by abrarsheikh** [Yelp/venv-update#140]
i run into the following trace when trying to rebuild the same tox target

specifically the issue is  the first install is fine, but the deps aren't being added on the second, so they get purged at the end

in the first run pip-faster installs all the dependancies [first run](http://pastebin.com/8iVTqYRE)
in the second run pip-faster installs only partial dependancies [second run](http://pastebin.com/w3EY5eTJ)

@bukzor pointed out that the issue could be here https://github.com/Yelp/venv-update/blob/development/pip_faster.py#L318

**Comment by asottile** [comment]
Could you paste some of your tox file so we can determine what is wrong?

**Comment by abrarsheikh** [comment]
@asottile link  to tox file http://pastebin.com/7JWhAJr2

**Comment by asottile** [comment]
Hmmm, the strange thing is it seems to uninstall the deps of sphinx (perhaps related to the circular tracing?).

It also seems to not notice most of the requirements in the second run that it noticed in the first run.  I also notice installing via `[extras]` which are an edgecase we've probably not tested sufficiently.  If I were a betting man, I'd wager that it has something to do with extras :)
