### ISSUE TITLE
Docs refer to out-of-date installation instructions

### ISSUE THREAD

**Issue by mesozoic** [Yelp/venv-update#164]
The ["Installation"](http://venv-update.readthedocs.io/en/stable/#installation) section instructs the user to run this set of commands:

```
curl https://yelp.github.io/venv-update/install.txt | bash
git add bin/venv-update
```

...which attempts to fetch a broken URL.

**Comment by bukzor** [comment]
@mesozoic If you browse to https://yelp.github.io/venv-update/install.txt does it 404 for you?
It works fine for me.

Closing this tentatively, but as always, feel free to reopen if I've gotten it wrong.
