### ISSUE TITLE
incorrect version references (rtfd, install script) and broken links (rtfd)

### ISSUE THREAD

**Issue by suntzu86** [Yelp/venv-update#175]
readthedocs:
http://venv-update.readthedocs.io/en/stable/
and the install script:
https://yelp.github.io/venv-update/install.txt
still reference v1.1.2.

Also, the links at the top of the readthedocs page all point to pip-faster pages, which seems confusing since the page and release version are for venv-update. Issues and Github redirect to venv-update pages on those sites, but the urls say pip-faster. [CircleCI 404s](https://circleci.com/gh/Yelp/pip-faster) and [PyPI shows pip-faster](https://pypi.python.org/pypi/pip-faster/) versions (vs [venv-update](https://pypi.python.org/pypi/venv-update)). Lastly, the travis-ci and circleci "colorful" links on the left navigation menu are inconsistent with github (showing failing or pointing at tree/stable, which doesn't seem to exist anymore).

**Comment by chriskuehl** [comment]
This should now be fixed, thanks!
