### ISSUE TITLE
Tests are too susceptible to bitrot

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/venv-update#197]
Two days ago I fixed a bunch of bitrot: aeb31b94d4a9d58ea5a7c095f955f38616baf55f

I just had to do it again: c08ad11bc5bee9d588dd38f66c8a89ad2e5b65b1

**Comment by ajm188** [comment]
Commas are important, yo

Do you mean that "tests are far too susceptible to bitrot" or "tests, too, are susceptible to bitrot" :trollface:

**Comment by bukzor** [comment]
Let's disambiguate "bitrot" and say "tests fails when various packages are upgraded on public pypi", which is a more actionable and obviously action-worthy ticket.

The solution that comes to mind is to add sufficient requirements to the test such that this will stop being the case. This will probably lose some coverage, but hopefully coverage-tool will point that out if so, and it can be corrected in the pypi-fixtured tests.

**Comment by asottile** [comment]
via d714ba7e26488d
