### ISSUE TITLE
pip-faster does not seem to respect --upgrade flag correctly

### ISSUE THREAD

**Issue by eagle-r** [Yelp/venv-update#223]
We have a project with a requirements (`requirements/base.txt`) file containing `Django==1.11.*` and a frozen requirements containing `Django==1.11.18`.

After running `venv-update venv= /path/to/venv install= -r requirements/base.txt`, we see the following command executed (as expected),
`pip-faster install --upgrade --prune -r requirements/base.txt`

but the output then shows,
```
Faster! pinned requirement already installed.
Requirement already up-to-date: Django==1.11.* in /path/to/venv/lib/python3.6/site-packages (from -r requirements/base.txt (line 3)) (1.11.15)
```

with the effect that it **downgrades** the version of Django instead of upgrading it to the most recent version (currently 1.11.20)

If we do a regular pip install with the same parameters it works as expected, however we then can't prune the unwanted packages.

**Comment by asottile** [comment]
heh, looks like an oversight in `pip-faster`.  For context, `pip-faster` was originally written targetting `pip 1.5` which was created in a time before [PEP 440](https://www.python.org/dev/peps/pep-0440/) existed (where the `==...*` syntax comes from).

This should be an easy fix if you're willing to submit a PR for it -- the bit that needs some adjustment currently lives here:

https://github.com/Yelp/venv-update/blob/02860446c983f8df10db221d66e22a7a912a550c/pip_faster.py#L98-L106

I can help write a test as well if you get stuck on that, the testsuite is a little overwhelming here

**Comment by eagle-r** [comment]
@asottile I'd appreciate any help you can provide with the tests as I'm not able to get them running on my mac

**Comment by asottile** [comment]
wrote a test for ya, and fixed the bitrot :+1:

**Comment by asottile** [comment]
via #224
