### ISSUE TITLE
venv-update gets into infinite exec loop when the Python binary comes from a OS X framework

### ISSUE THREAD

**Issue by chriskuehl** [Yelp/venv-update#227]
Or something like that, I didn't fully track it down. It appears to be related to the `__PYVENV_LAUNCHER__` environment variable: https://stackoverflow.com/a/53193892

The problem is that this environment variable is still set when we try to exec the scratch Python here, which causes this exec statement to be hit in a loop:
https://github.com/Yelp/venv-update/blob/afe9886b7481de770f2a684ec7450368006d54f3/venv_update.py#L212-L214

If we clear that variable manually before the exec, it fixes it. So does making sure that the `python` binary on the PATH didn't come from a OS X "framework". (In this case, there was a homebrew-installed Python 3.7 at `/usr/local/bin/python`.)

Sorry, no reproduction steps right now -- I reproduced this on another person's laptop and didn't want to spend too long trying to reproduce it locally given the maintenance status of venv-update. Here's some output from print statements added right before the exec:

```
$ make deps
./bin/venv-update \
				  venv= --python=python3.7 venv -vvv \
				  bootstrap-deps= -r requirements-bootstrap.txt -vvv \
				  install= -r requirements-dev.txt -vvv
realpath(sys.prefix): /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7
realpath(scratch.venv): /Users/REDACTED/.cache/venv-update/3.0.0/venv
realpath(sys.prefix): /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7
realpath(scratch.venv): /Users/REDACTED/.cache/venv-update/3.0.0/venv
realpath(sys.prefix): /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7
realpath(scratch.venv): /Users/REDACTED/.cache/venv-update/3.0.0/venv
realpath(sys.prefix): /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7
realpath(scratch.venv): /Users/REDACTED/.cache/venv-update/3.0.0/venv
realpath(sys.prefix): /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7
realpath(scratch.venv): /Users/REDACTED/.cache/venv-update/3.0.0/venv
realpath(sys.prefix): /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7
realpath(scratch.venv): /Users/REDACTED/.cache/venv-update/3.0.0/venv
realpath(sys.prefix): /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7
realpath(scratch.venv): /Users/REDACTED/.cache/venv-update/3.0.0/venv
```

(internal reference: WEBCORE-8421)

**Comment by asottile** [comment]
pre-commit had the same problem, here was the fix there: https://github.com/pre-commit/pre-commit/blob/0fd4a2ea38df4f276e43397e21ecb3fcbc96d122/pre_commit/main.py#L32-L36

**Comment by chriskuehl** [comment]
We found another way this can cause breakage which isn't an infinite exec loop: when venv-update tries to install bootstrap deps, it imports pip libraries from the wrong path due to `__PYVENV_LAUNCHER__` which causes an import error. (Sorry, no traceback, was debugging this over somebody's shoulder on another laptop.)

@asottile's fix worked, I'm going to make a PR.
