### ISSUE TITLE
venv-update update of pip contrains

### ISSUE THREAD

**Issue by theodore86** [Yelp/venv-update#237]
Hi,

Request is like an enhance rather than an issue, is it possible to change the venv-update setup.py requirements for pip? At the moment venv-update requires: ``pip>=10.0.0,<=18.1`` but it seems that some python packages like ``cryptography requires pip>=19.1`` (at least for ``cryptography > 3.2.2``). Is it feasible to go for pip: `` pip>=10.0.0,<=19.1`` without breaking the existing functionality?

Thanks in advance,
Theodore G.

**Comment by asottile** [comment]
it's constrained because it does not work with pip 19.1+
