### ISSUE TITLE
support pip6

### ISSUE THREAD

**Issue by bukzor** [Yelp/venv-update#27]
Full disclosure: While we do intend to start using a modern pip in v2, it's
not currently a high priority.
This means probably a 6-12 month period before this happens.
However, if anyone in the community takes it upon themselves and can make
the test suite pass, we'll gladly merge.

**Comment by adamchainz** [comment]
I was surprised to try this and be pushed back from pip 8.1.0 to pip 1.5.6, after which `venv-update` crashed because my requirements file doesn't work with 1.5.6

**Comment by bukzor** [comment]
Sorry. What is it specifically that fails?

**Comment by adamchainz** [comment]
The old `pkg_resources` can't parse the new-style version description in one of our dependencies:

```
Exception:
Traceback (most recent call last):
  File "/path/to/venv/local/lib/python2.7/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/path/to/venv/local/lib/python2.7/site-packages/pip_faster.py", line 475, in run
    requirement_set = super(FasterInstallCommand, self).run(options, args)
  File "/path/to/venv/local/lib/python2.7/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/path/to/venv/local/lib/python2.7/site-packages/pip_faster.py", line 387, in prepare_files
    super(FasterRequirementSet, self).prepare_files(finder, **kwargs)
  File "/path/to/venv/local/lib/python2.7/site-packages/pip/req.py", line 1229, in prepare_files
    req_to_install.run_egg_info()
  File "/path/to/venv/local/lib/python2.7/site-packages/pip/req.py", line 330, in run_egg_info
    "%(Name)s==%(Version)s" % self.pkg_info())
  File "/path/to/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2667, in parse
    reqs = list(parse_requirements(s))
  File "/path/to/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2605, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/path/to/venv/local/lib/python2.7/site-packages/pip/_vendor/pkg_resources.py", line 2583, in scan_list
    "Expected ',' or end-of-list in",line,"at",line[p:]
ValueError: ("Expected ',' or end-of-list in", u'django-codemirror-widget==0.4.0+yplan.1', 'at', u'+yplan.1')
```

This is a package we've forked and added the `+yplan.1` on the version number to differentiate it: https://github.com/Aaron7/django-codemirror-widget/blob/0.4.0%2Byplan.1/setup.py#L9 . It's being installed from github with `https://github.com/Aaron7/django-codemirror-widget/archive/c6ef86ca691b07c30f48bd21e49f8dc86e8c3afa.tar.gz`.

**Comment by bukzor** [comment]
I wasn't familiar with the idea of "local" releases versus "post" releases
til today. TIL.

Full disclosure: While we do intend to start using a modern pip in v2, it's
not currently a high priority.
This means probably a 6-12 month period before this happens.
However, if anyone in the community takes it upon themselves and can make
the test suite pass, we'll gladly merge.

**Comment by drolando** [comment]
pip 1.5.x also doesn't work well with pypy wheels. It keeps telling me that those wheels are not supported on this platform. I don't know when that got fixed, but the same wheels install fine with the latest pip.

I was looking into adding support for pip >= 6.0: it could be done just by adding a few if / else in the existing code to support the new interface. However most functions in pip_faster.py are copy pasted from pip==1.5.6 with just a few changes, so patching them doesn't seem the right solution.
The same functions in pip==9.0.1 have a completely different code (and usually more complex) so we'd probably loose some new functionality.

@asottile @bukzor Any suggestion? Should we have a new pip_faster_v2.py script for pip >= 6 with the most recent code patched?

**Comment by chriskuehl** [comment]
I don't think it's necessary to support old pip? Only the bootstrap phase has restricted dependencies, and only on virtualenv. venv-update should be free to depend on whatever version of pip it likes inside the created virtualenv afaik.

**Comment by drolando** [comment]
> Only the bootstrap phase has restricted dependencies, and only on virtualenv.
Not really, we use pip_faster also after the bootstrap to install the real dependencies. If you have pip>=6 pip_faster will break because the interface is different.

> I don't think it's necessary to support old pip
Are you saying I can drop support for pip < 6.0.0 and rewrite the code to match the newer version?

**Comment by asottile** [comment]
Yep!  No need to support old pip

**Comment by asottile** [comment]
Also, I think we lifted the restriction on virtualenv version during bootstrap phase as well!

**Comment by drolando** [comment]
#166
