### ISSUE TITLE
erronious files touched

### ISSUE THREAD

**Issue by NorthIsUp** [Yelp/venv-update#34]
`run(('touch', venv_path, '--reference', reqs[0], '--date', '1 day ago'))` creates a `--date`, `--reference`, and `1 day ago` file in my path.

**Comment by NorthIsUp** [comment]
looks like BSD touch vs GNU touch

**Comment by bukzor** [comment]
Yea I have GNU touch exposed on my OSX box via a homebrew hack.

I assume you're on OSX?

**Comment by bukzor** [comment]
If you can craft a command that works equally with BSD and GNU, that'd be ideal.
Or I suppose I could implement it in python.
This started as a makefile rule =X

**Comment by bukzor** [comment]
Seems like both would accept `-t 197001010000`
