### ISSUE TITLE
does not install packages marked with -e editable

### ISSUE THREAD

**Issue by NorthIsUp** [Yelp/venv-update#36]
installs: `git+ssh://whatever#egg=whatever`
doesn't install: `-e git+ssh://whatever#egg=whatever`

**Comment by bukzor** [comment]
How do I verify that it's broken/fixed?

**Comment by NorthIsUp** [comment]
`pip freeze | grep whatever`

**Comment by NorthIsUp** [comment]
This appears to be invalid.

It turns out -e is not supported with archive urls. So this is a feature of pip, not a bug in venv_udpate.

**Comment by bukzor** [comment]
What is an archive url? A tar.gz?

**Comment by NorthIsUp** [comment]
Yes.

`-e https://github.com/Yelp/venv-update/archive/master.zip` would not work
`-e git+https://github.com/Yelp/venv-update.git#egg=venv_update` would work
