### ISSUE TITLE
make venv_update updatable

### ISSUE THREAD

**Issue by NorthIsUp** [Yelp/venv-update#37]
My leading idea is "why not use pip?". It mentions in the readme that this was not done intentionally, could someone add more info as to why?

The setup.py supports entry_points so that says to me the project is intended to be installed, why not make it network updatable too?

**Comment by bukzor** [comment]
Since venv-update is meant to be the code that runs pip, pip can't be the only way to install it.

You certainly can install it, and it should work that way.

Is your main complaint that I haven't posted to pypi?

**Comment by NorthIsUp** [comment]
yeah, its not on pypi.

My current work flow is `curl -O https://raw.githubusercontent.com/Yelp/venv-update/master/venv_update.py`

Ideally I could use pip install venv_update --upgrade, or even better, pin it to a specific version. Both of which publishing to pypi support.

As for the chicken/egg problem I don't have any good ideas there yet.

**Comment by bukzor** [comment]
https://pypi.python.org/pypi/venv-update/0.1.1

**Comment by bukzor** [comment]
Note this is still very much beta.
I've laid out the points I consider blocking for v1.0 in the TODO.

**Comment by asottile** [comment]
wellp, you didn't actually upload it, you just registered it.

**Comment by asottile** [comment]
```
$ pip install venv-update
Downloading/unpacking venv-update
  Downloading venv-update-0.1.1.tar.gz
  Storing download in cache at /home/asottile/.pip/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fsource%2Fv%2Fvenv-update%2Fvenv-update-0.1.1.tar.gz
  Running setup.py (path:/home/asottile/workspace/venv-update/venv2/build/venv-update/setup.py) egg_info for package venv-update
    
Downloading/unpacking virtualenv>=1.11.5,<2.0 (from venv-update)
  Downloading virtualenv-1.11.6-py2.py3-none-any.whl (1.6MB): 1.6MB downloaded
  Storing download in cache at /home/asottile/.pip/cache/https%3A%2F%2Fpypi.python.org%2Fpackages%2Fpy2.py3%2Fv%2Fvirtualenv%2Fvirtualenv-1.11.6-py2.py3-none-any.whl
Installing collected packages: venv-update, virtualenv
  Running setup.py install for venv-update
    
    Installing venv-update script to /home/asottile/workspace/venv-update/venv2/bin
Successfully installed venv-update virtualenv
Cleaning up...
```
