### ISSUE TITLE
`run(('rm', '-rf', venv_path))` is worrisome

### ISSUE THREAD

**Issue by NorthIsUp** [Yelp/venv-update#39]
`run(('rm', '-rf', venv_path))`

I was considering putting some checks around this line to ensure that we don't delete something important, like `/`, or `.`, or `..`.

thoughts?

**Comment by asottile** [comment]
That would feel over engineered to me.

**Comment by NorthIsUp** [comment]
https://github.com/ValveSoftware/steam-for-linux/issues/3671

**Comment by asottile** [comment]
The difference there is steam is consumer software and this is a development tool.

**Comment by NorthIsUp** [comment]
I think a similar scenario would be very easy to imagine. The solution doesn't need to be complicated either, a simple `assert(path and path not in ('/', '.', '..'))` would be sufficient.

**Comment by asottile** [comment]
I'll let @bukzor decide but my vote is -1.  It's simply not possible to enumerate all dangerous paths.

**Comment by bukzor** [comment]
The rm command (at least GNU) seems to already have those protections built in:


```
$ ls
coverage.txt  fub.pl  pip.log
$ rm -rf ''
$ rm -rf .
rm: cannot remove directory: ‘.’
$ rm -rf ..
rm: cannot remove directory: ‘..’
$ rm -rf /
rm: it is dangerous to operate recursively on ‘/’
rm: use --no-preserve-root to override this failsafe
$ ls
coverage.txt  fub.pl  pip.log
```

It wouldn't hurt to protect them twice, to help our osx friends though. If you write a patch, show the test suite passing, I'll merge it.

**Comment by NorthIsUp** [comment]
My main worry was what happens in the event `venv_path` is empty. I'll close this for now and re-open it if I make a patch.

**Comment by bukzor** [comment]
In that case, it force-removes an empty-string file, resulting in no change, unless you somehow had a file named empty-string. Actually, it would have to be a directory, since this is guarded by isdir.
