### ISSUE TITLE
double requirement: argparse==1.2.1

### ISSUE THREAD

**Issue by tgs** [Yelp/venv-update#47]
argparse is required in my requirements.txt, and `pip wheel` gets mad and stops.

    Double requirement given: argparse==1.2.1 (from -r requirements.txt (line 5)) (already in argparse==1.2.1, name='argparse')

Of course, I can take it out for the moment

**Comment by bukzor** [comment]
imho it's not a conflict when the exact same requirement is specified twice.

What would be your preferred solution?

**Comment by tgs** [comment]
I know, it seems really silly!  I don't know enough about pip to have a solution, unfortunately.  I would understand if it's a "wontfix" for now.

**Comment by bukzor** [comment]
It's fine, just wanted your guess :)

I'll leave it open and take a look next time I sprint on this thing.
